language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
install:
  - rustup component add rustfmt-preview clippy-preview || true
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
jobs:
  include:
    - stage: format
      rust: beta
      rust: stable
      script: cargo fmt --all -- --check && cargo clippy
    - stage: deploy
      rust: stable
      script: cargo doc --all --release
      deploy:
        provider: pages
        local-dir: target/doc/
        project-name: mandelbrot
        target-branch: gh-pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
stages:
  - test
  - format
  - name: deploy
    if: branch = master
