language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
install:
  - rustup component add rustfmt-preview clippy-preview
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - env: FMT=true
    - env: DOC=true
      rust: stable
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - "[ ${FMT+x} ] && { cargo fmt --all -- --check && cargo clippy; } || [ ! ${FMT+x} ]"
  - "[ ${DOC+x} ] && { cargo doc --all --bins --release && ls -latrh; } || [ ! ${DOC+x} ]"
deploy:
  local-dir: target/doc/
  provider: pages
  project-name: mandelbrot
  target-branch: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    condition: $DOC = true
